@startuml
participant "VSCode" as V
participant "GitHub" as G
participant "GitHub Actions" as GA
participant "ScratchOrg" as S

V -> G : git push
G -> GA : on push
GA -> S : sf project deploy start
S --> GA : response
@enduml